model:
  vocab_size: 1000
  d_model: 384
  n_layers: 6
  n_heads: 6
  d_ff: 1536
  dropout: 0.1
  block_size: 256

train:
  learning_rate: 3e-4
  warmup_steps: 10
  max_steps: 50
  batch_size: 4
  grad_accumulation_steps: 1
  grad_clip: 1.0
  amp: false
  use_compile: false
  use_gradient_checkpointing: false
  log_interval: 10
  eval_interval: 25
  save_interval: 25

data:
  train_path: data/tiny_shakespeare_train.txt
  val_path: data/tiny_shakespeare_val.txt
  block_size: 256

tokenizer:
  vocab_size: 1000 